#ifndef OLAM_DATA_TABLE_H
#define OLAM_DATA_TABLE_H

#define DXL_SERIAL Serial3
#define COM_SERIAL Serial
#define DEBUG_SERIAL Serial
#define DEBUG_SERIAL_CLASS USBSerial

//Pin
#define PIN_DXL_DIR 22
#define TC_PIN_LIMIT_SWITCH_LOW_NO 10
#define TC_PIN_LIMIT_SWITCH_LOW_NC 11
#define TC_PIN_LIMIT_SWITCH_HIGH_NO 12
#define TC_PIN_LIMIT_SWITCH_HIGH_NC 15

#define TC_SERVO_ENCODER_BIT 4096

#define TC_VELOCITY_MAX 1022
#define TC_VELOCITY_INC 30
#define TC_VELOCITY_INITIAL 1022
#define TC_LOOSE_LINE_ROT_COUNT 10
#define TC_TENSIONING_ROT_DIR -1

//Dxl servo firmware settings
#define MOTOR_ID_LTC 1
#define MOTOR_ID_AC 2
#define DXL_PROTOCOL_VERSION 2.0
#define DXL_BAUD_RATE 57600

//Communication
#define OLAM_MAV_SYS_ID 1
#define OLAM_MAV_COMP_ID MAV_COMP_ID_USER32
#define OLAM_MAV_BAUDRATE 57600
#define GCS_MAV_SYS_ID 1
#define GCS_MAV_COMP_ID 240

#define OLAM_MAV_MSG_DEBUG_VECT_NAME_STATUS_REPORT "OLAMS"
#define OLAM_MAV_MSG_ID_NOT_FOR_US 9999999u
#define OLAM_MAV_MSG_BUTTON_CHANGE_PASSCODE 32467
#endif